language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer install

script:
  - ./vendor/bin/php-cs-fixer fix --diff --verbose --dry-run
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - ./vendor/bin/phpstan analyse

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
